### ISSUE TITLE
Null pointer with processor framework barrels after saving/reloading a game

### ISSUE THREAD

**Issue by gbl** [Syrchalis/ProcessorFramework#2]
I ran into this issue, and saw some talk on Steam about it. Maybe I can shed a little light on it?

First, I had Processor Framework *and* Universal Fermenter loaded. Probably shouldn't have. Not sure if this may be one of the reasons for the bug. And maybe there are mods out which pull one of them in, and other mods pulling the other in, so others might have the same config.

What happened to me is:

- One pawn made 5 wort which got put into the barrel
- another pawn put some more wort into the same barrel after the first part had been working for a bit
Result:
![image](https://user-images.githubusercontent.com/243563/151700692-59c202cb-ad28-4e75-9ad5-0b247667d85a.png)
and in another barrel:
![image](https://user-images.githubusercontent.com/243563/151700710-4d56a3df-b651-49e5-999d-22f417d09ea0.png)

Note how both of them say "wort, wort" in the content description. 

This shows up in the save file as
```
                                                <PF_activeProcesses>
                                                        <li>
                                                                <PF_processDef>Beer</PF_processDef>
                                                                <ingredientThings>
                                                                        <li>Thing_Wort1143505</li>
                                                                        <li>null</li>
                                                                </ingredientThings>
                                                                <PF_ingredientCount>15</PF_ingredientCount>
                                                                <PF_activeProcessTicks>3667</PF_activeProcessTicks>
                                                                <targetQuality>Awful</targetQuality>
                                                        </li>
                                                </PF_activeProcesses>
```

and 
```
                                                <PF_activeProcesses>
                                                        <li>
                                                                <PF_processDef>Beer</PF_processDef>
                                                                <ingredientThings>
                                                                        <li>Thing_Wort1143429</li>
                                                                        <li>null</li>
                                                                </ingredientThings>
                                                                <PF_ingredientCount>14</PF_ingredientCount>
                                                                <PF_activeProcessTicks>4268</PF_activeProcessTicks>
                                                                <targetQuality>Awful</targetQuality>
                                                        </li>
                                                </PF_activeProcesses>
```
and the save file also has a barrel that I didn't notice before saving which seems to have been filled 4 times that has
```
                                                <PF_activeProcesses>
                                                        <li>
                                                                <PF_processDef>Beer</PF_processDef>
                                                                <ingredientThings>
                                                                        <li>Thing_Wort1143411</li>
                                                                        <li>null</li>
                                                                        <li>null</li>
                                                                        <li>null</li>
                                                                </ingredientThings>
                                                                <PF_ingredientCount>25</PF_ingredientCount>
                                                                <PF_activeProcessTicks>11800</PF_activeProcessTicks>
                                                                <targetQuality>Awful</targetQuality>
                                                        </li>
                                                </PF_activeProcesses>
```

After loading the game, this leads, probably as should be expected, to
![image](https://user-images.githubusercontent.com/243563/151700882-23f01a81-1302-4422-b998-ae118365190d.png)
and
![image](https://user-images.githubusercontent.com/243563/151700895-a29a7650-0684-4af7-9f62-ac0db2ce1c2b.png)

If I remove the extra `<li>null</li>` rows from the save file before loading, the barrels seem ok.

So there might be some issues with the code that detects merging "old content" with "newly filled content" in that it merges the new content into the existing one, and adds the amount together, but sets the new content to null instead of removing it from the list (or maybe has the two list entries point to the same object, which explains the "wort, wort" being shown, and only sets the extra list entries pointing to the same object to bull while saving).

**Comment by gbl** [comment]
Two updates:
- removing universal fermenter from the mod list, fixing the save file by removing the `<li>null</li>` entries, then continuing to play didn't fix the underlying issue; after a pawn filled another barrel, that barrel still had the double content entry
- I guess the bug is in line 130 in `ActiveProcess.cs`, (method MergeProcess) which adds `Thing` to `ingredientThings` even after adjusting the amount and progress fields. Unfortunately, I'm on Linux, so I can't just download visual studio and compile the thing to try it out.

**Comment by Syrchalis** [comment]
I'll take a look, the save file thing is very helpful to see where the issue is coming from.

**Comment by Syrchalis** [comment]
Potentially fixed it with the last update.
