### ISSUE TITLE
Unoptimized search function

### ISSUE THREAD

**Issue by nickleno1** [Syrchalis/ProcessorFramework#3]
The WorkGiver is using a resource heavy process to find ingredients for the processor jobs.

In [WorkGiver_FillProcessor.cs:96](https://github.com/Syrchalis/ProcessorFramework/blob/main/Source/ProcessorFramework/WorkGiver_FillProcessor.cs#L96) you're calling the ClosestThingReachable method with the HaulableEver ThingRequestGroup. Because of how that method is implemented, the game will calculate the relative distances of every haulable item on the map before checking to see if those items can actually be used with the processor.

I created a fix for this. Instead of searching all haulable items, I'm restricting it to only items which are valid ingredients for unfilled enabled processes. This significantly reduces unnecessary calculations. I've tested it on its own and with some additional mods that are built on the framework, performance is noticeably better.

I can send you the code changes for this if you like.

**Comment by Syrchalis** [comment]
If you go through the trouble to post this on GitHub, please make a pull request so I can review the code.

**Comment by Syrchalis** [comment]
Implemented my own fix.

Did some advanced testing and found the issue be a lot of idling pawns constantly triggering the workGiver and thus constantly checking for items on the map. Additionally this only happens on sufficiently large maps (I test on 75x75 usually for faster loading). Implemented a lookup method in the map component that caches the valid ingredients and prevents it from running more than once every 5 seconds.

This completely nullifies the performance impact, even at very high pawn counts and a large map.
